#!/usr/bin/bash
xhost +local:docker 

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
touch $XAUTH
if [ ! -f $XAUTH ]
then
    xauth_list=$(xauth nlist :0 | sed -e 's/^..../ffff/')
    if [ ! -z "$xauth_list" ]
    then
        echo $xauth_list | xauth -f $XAUTH nmerge -
    else
        touch $XAUTH
    fi
    chmod a+r $XAUTH
fi

data_path1=/mnt/bigbertha_mount/GithubWorkspace/ContourPose/data
data_path2=/mnt/bigbertha_mount/data
repo_path=/mnt/bigbertha_mount/GithubWorkspace/ContourPose-Baseline
container_name=contourpose-baseline-4090
img_name=$container_name

# --volume=/mnt/bigbertha_mount/data/Datasets/ContourPose/SUN2012pascalformat:/data/Datasets/ContourPose/SUN2012pascalformat \

docker stop $container_name & docker container rm $container_name 

docker run -it \
	--name $container_name \
	--volume=$XSOCK:$XSOCK:rw \
        --volume=$XAUTH:$XAUTH:rw \
	-p=9000:9000/tcp \
	-p=7000:7000/tcp \
        --volume=/dev:/dev \
        --privileged \
        --volume=$repo_path:/$container_name \
	--volume=$data_path1:/$container_name/data \
	--volume=$data_path2:/data \
        -w /$container_name \
	--env="XAUTHORITY=$XAUTH" \
	--env="DISPLAY=$DISPLAY" \
	--env="QT_X11_NO_MITSHM=1" \
	--runtime=nvidia \
	--net=host --gpus all \
	--env="NVIDIA_DRIVER_CAPABILITIES=all" \
	$img_name \
	bash
